
GET http://localhost:3000/api/users/whoami
Accept: application/json

###
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "name": "Tester Testerson",
    "password": "12345678",
	"email": "test2@test.com"
}

###
POST http://localhost:3000/api/users/loginff
Content-Type: application/json

{
    "password": "123456781",
	"email": "test2@test.com"
}

###
POST http://localhost:3000/api/users/logout


###
POST http://localhost:3000/api/links/generate
Content-Type: application/json

{
    "url": "https://www.google.com"
}

###
GET http://localhost:3000/api/links/get
Accept: application/json

