version: "3.9"
services:
  apiServer:
    env_file:
      - ./server/.env.prod
    image: "uflock/primarybid-api-server"
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production
    ports:
        - "3000:3000"
    networks:
      - frontend
      - backend
  client:
    image: "uflock/primarybid-simple-client"
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
    ports:
        - "80:80"
    networks:
      - frontend
  mongo-db:
    image: "mongo"
    command: mongod --quiet --logpath /dev/null
    ports:
        - "27017:27017"
    networks:
      - backend
networks:
  frontend:
  backend:
