version: "3.9"
services:
  apiServer:
    image: "uflock/primarybid-api-server"
    links:
      - mongo-db
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./server:/server
      - /server/node_modules/
    ports:
        - "3000:3000"
  mongo-db:
    image: "mongo"
    command: mongod --quiet --logpath /dev/null
    ports:
        - "27017:27017"
